/* Database schema to keep the structure of entire database. */

CREATE TABLE IF NOT EXISTS animals (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name varchar(100) NOT NULL,
  date_of_birth date NOT NULL,
  escape_attempts integer NOT NULL,
  neutered boolean NOT NULL,
  weight_kg decimal(5,2) NOT NULL
);

ALTER TABLE animals
  ADD COLUMN species varchar(100)
;

CREATE TABLE IF NOT EXISTS owners (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  full_name varchar(100) NOT NULL,
  age int,
  primary key (id)
);

CREATE TABLE IF NOT EXISTS species (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name varchar(100) NOT NULL,
  primary key (id)
);

ALTER TABLE animals
  ADD primary key (id)
;

ALTER TABLE animals
  DROP COLUMN species
;

ALTER TABLE animals
  ADD COLUMN species_id int,
  ADD COLUMN owner_id int,
  ADD CONSTRAINT fk_species FOREIGN KEY (species_id) REFERENCES species(id),
  ADD CONSTRAINT fk_owners FOREIGN KEY (owner_id) REFERENCES owners(id)
;